language: mysql
dialect: 5.7
resources:
  - "schema/**/*.sql"
queries:
  - "src/dao/**/*.ts"
  - "!src/**/*.test.ts"
  - "!src/**/*.test.integration.ts"
generates: src/dao/common/generated/fromSql # a directory path
